name: Deploy Next.js to EC2
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
    
    - name: Build Next.js application
      run: npm run build
      env:
        NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
        NEXT_PUBLIC_COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
        NEXT_PUBLIC_COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      run: |
        # Create deployment package
        tar -czf deployment.tar.gz .next node_modules public package.json package-lock.json next.config.ts
        
        # Copy deployment package to EC2
        scp deployment.tar.gz ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/tmp/
        
        # Run deployment commands on EC2
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOL'
          # Stop the current application
          pm2 stop next-app || echo "App not running yet"
          
          # Clean up previous deployment
          rm -rf /var/www/html/cog-ui-test/.next
          
          # Extract the new deployment
          tar -xzf /tmp/deployment.tar.gz -C /var/www/html/cog-ui-test/
          
          # Restart the application
          cd /var/www/html/cog-ui-test
          pm2 restart next-app || pm2 start npm --name "next-app" -- start
          
          # Clean up
          rm /tmp/deployment.tar.gz
          
          # Ensure Nginx is running
          sudo systemctl restart nginx
        EOL
        
    - name: Deployment Summary
      run: |
        echo "🚀 Deployment Summary:"
        echo "- Next.js deployment completed"
        echo "- Application deployed to: http://${{ secrets.EC2_HOST }}"